name: CI
on: [push, pull_request]

jobs:
  stable-and-nightly:
    name: Stable and nightly
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [stable, nightly]
        neovim: [true, false]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          version: ${{ matrix.version }}
          neovim: ${{ matrix.neovim }}
        id: vim
      - name: Validate action result
        run: node ./scripts/post_action_check.js "${{ matrix.neovim }}" "${{ matrix.version }}" "${{ steps.vim.outputs.executable }}"

  # separate from stable-and-nightly since jobs.{id}.name.strategy.matrix.exclude seems not working
  vim-v8_2_1931:
    name: Vim v8.2.1931
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          version: v8.2.1931
        id: vim
      - name: Validate action result
        run: node ./scripts/post_action_check.js "false" "v8.2.1931" "${{ steps.vim.outputs.executable }}"
  nvim-v0_4_4:
    name: Neovim v0.4.4
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          neovim: true
          version: v0.4.4
        id: neovim
      - name: Validate action result
        run: node ./scripts/post_action_check.js "true" "v0.4.4" "${{ steps.neovim.outputs.executable }}"
  # See #10 for more details. Vim older than 8.2.1119 cannot be built with Xcode 12 or later.
  vim-v8_1_2424-mac:
    name: Vim v8.1.2424
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          version: v8.1.2424
        id: vim
      - name: Validate action result
        run: node ./scripts/post_action_check.js "false" "v8.1.2424" "${{ steps.vim.outputs.executable }}"

  test-and-lint:
    name: Check unit tests and linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci
      - name: Run unit tests
        run: npm test
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: npm run lint
      - uses: actions/setup-python@v4
      - run: pip install yamllint
      - run: yamllint --strict .github/workflows
      - name: Check workflow files
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
